package com.mds2.foro;

//import Package2.iAdministrador;

public class Administrador extends Banner_general {
	public iAdministrador _iAdministrador;
	public Lista_Tema_V_Administrador _tema_vista_administrador;
	public Lista_Mensaje_V_Administrador _mensaje_vista_administrador;
	public Lista_Seccion_V_administrador _unnamed_Lista_Seccion_V_administrador_;
	public Panel_de_administración_vista_administrador _unnamed_Panel_de_administración_vista_administrador_;
}