package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Lista_Mensaje_ventana extends VerticalLayout {
	protected VerticalLayout textoMensajeCreacion;
	protected Button volverTema;
	protected Button crearMensaje;
	protected TextField buscadorMensaje;
	protected Button buscadorBoton;
	protected Label subtitle;
	protected Label numMensajes;
	protected Label usuarioCreador;
	protected Label fechaCreacion;
	protected VerticalLayout listaMensajeAdmin;

	public Lista_Mensaje_ventana() {
		Design.read(this);
	}
}
