package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_Administrador_ventana extends VerticalLayout {
	protected VerticalLayout textoMensajeCreacion;
	protected Button volverTema;
	protected Button crearMensaje;
	protected TextField buscadorMensaje;
	protected Button buscadorBoton;
	protected Label subtitle;
	protected Label numMensajes;
	protected Label usuarioCreador;
	protected Label fechaCreacion;
	protected Image fotoPerfil;
	protected Label nombreUsuario;
	protected TextField contenidoMensaje;
	protected CheckBox meGusta;
	protected Button eliminarMensaje;
	protected Button responderMensaje;
	protected Label fechaCreacionMsg;
	protected Image fotoPerfil1;
	protected Label nombreUsuario1;
	protected TextField contenidoMensaje1;
	protected CheckBox meGusta1;
	protected Button eliminarMensaje1;
	protected Button responderMensaje1;
	protected Label fechaCreacionMsg1;

	public Mensaje_Administrador_ventana() {
		Design.read(this);
	}
}
