package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_Vista_Admin_ventana extends VerticalLayout {
	protected Label tituloTema;
	protected Button crearMensaje;
	protected Label subtitulo;
	protected Label numMensajes;
	protected Label userOwner;
	protected Label date;
	protected HorizontalLayout seccion;
	protected Label nick1;
	protected Panel texto;
	protected HorizontalLayout seccion2;
	protected Button eliminarMensaje;
	protected Button responderMensaje;
	protected Panel fechaMensaje;
	protected HorizontalLayout seccion1;
	protected Label nick11;
	protected Panel texto1;
	protected HorizontalLayout seccion21;
	protected Button eliminarMensaje1;
	protected Button responderMensaje1;
	protected Panel fechaMensaje1;

	public Mensaje_Vista_Admin_ventana() {
		Design.read(this);
	}
}
