package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_Administrador_ventana extends VerticalLayout {
	protected Image fotoPerfil;
	protected Button irPerfil;
	protected TextField contenidoMensaje;
	protected Button meGustaB;
	protected Button eliminarMensaje;
	protected Button responderMensaje;
	protected Button notificarAdminB;
	protected Label fechaCreacionMsg;

	public Mensaje_Administrador_ventana() {
		Design.read(this);
	}
}
