package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PaginaPrincipal_ventana extends VerticalLayout {
	protected VerticalLayout banner;
	protected Panel panelMenu;
	protected Panel panelMain;
	protected Panel panelPublicidad;
	protected VerticalLayout bannerAbajo;

	public PaginaPrincipal_ventana() {
		Design.read(this);
	}
}
