package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrarse_ventana extends FormLayout {
	protected TextField userNameRegistro;
	protected PasswordField password;
	protected TextField emailRegistro;
	protected Label email;
	protected TextField nombreCompleto;
	protected TextField descripcion;
	protected Upload uploadImage;
	protected Button registro;
	protected Button enlaceIniciarSesion;

	public Registrarse_ventana() {
		Design.read(this);
	}
}
