package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Seccion_Admin_ventana extends VerticalLayout {
	protected VerticalLayout seccionVentana;

	public Seccion_Admin_ventana() {
		Design.read(this);
		Seccion_Admin_lista SAl = new Seccion_Admin_lista();
		addComponent(SAl);
	}
}
