package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SeccionVistaAdministrador_ventana extends VerticalLayout {
	protected Button crearNuevaSeccion;
	protected HorizontalLayout seccion;
	protected ComboBox<java.lang.String> statusTema;
	protected HorizontalLayout seccion2;
	protected HorizontalLayout seccion1;
	protected ComboBox<java.lang.String> statusTema1;
	protected HorizontalLayout seccion21;

	public SeccionVistaAdministrador_ventana() {
		Design.read(this);
	}
}
