package com.mds2.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visita_Perfil_Admin_ventana extends VerticalLayout {
	protected HorizontalLayout datosVisitaPerfil;
	protected Image fotoPerfilUsuario;
	protected TextField nombreUsuario;
	protected TextField descripcionUsuario;
	protected Button interaccionarAmigoUsuario;
	protected Button interaccionarSancionAdmin;
	protected Button interaccionarModeracionAdmin;
	protected TextField estadoUsuarioMod;

	public Visita_Perfil_Admin_ventana() {
		Design.read(this);
	}
}
